### ISSUE TITLE
task.status vs task.progress

### ISSUE THREAD

**Issue by assembledStarDust** [GALAglobal/TAPICC-API-implementation#36]
` POST /asset/{parentid}/task `Create a Task
wrt: task.progress - its referred to as status in the description. Why not call it status then.

return snippet for reference
```
{
  "id": 0,
  "type": "translation",
  "targetLanguage": "string",
  "progress": "pending",
  "assignedTo": "string",
  "file": "string",
......
```

wrt: task status (as per description)
"paused" can mean too many things.
suggest add status type "blocked"
"paused" - the vendor has responsibility for the task but has stopped working on it for any reason.
"blocked" - the system has responsibility for the task but has stopped any action on it for any reason. A hypothetical example reason might be that the downloadablefile might be in progress for being created.

edit: related to [issue 28](https://github.com/GALAglobal/TAPICC-API-implementation/issues/28)

**Comment by Alino** [comment]
this issue seems as duplicate of #28 (if we implement the first suggestion by yves, then task.progress will get renamed to task.status)

----

regarding Task.paused and Task.blocked

for reference 

```
      Task can have these statuses:

      pending - the Task has been created, and it's pending to be reviewed and assigned to someone.

      in progress - the Task has been assigned to someone and is being worked on.

      paused - the Task went from in progress, to paused, because something is blocking the Task, or the assignee has other priorities.

      canceled - someone did cancel this Task.

      finished - the work on this Task is done and deliverableLocation is filled with a path to deliverable.
```

I see no reason to have two similar Task statuses (paused vs blocked) both are paused for any reason.

Sorry I didn't understand your hypothetical example. I think when a Task deliverable is not yet created, then the Task.progress is likely set to 'in progress' if the assignee is working on it.

**Comment by assembledStarDust** [comment]
agree that this issue is a duplicate of #28.

I will carry on the conversation regarding additional task statuses in that issue.

This issue can be closed.
