### ISSUE TITLE
Types of task

### ISSUE THREAD

**Issue by ysavourel** [GALAglobal/TAPICC-API-implementation#43]
Currently a task can have one of four values:
- translation
- machine translation
- modification
- proof

I would suggest to have very precise definition of each type. I'm not sure what `modification` means: all of those tasks are modifying the input asset. Also, what about review? QA? post-editing? etc.

**Comment by Alino** [comment]
I think these task types were just some initial mockup, this issue is a good reminder to improve it.
Here is a link to a document created by Serge related to Task types -> https://docs.google.com/document/d/1POWcoIrwKvUQpgq_ImgcpK_p6PZ35k7g7mieKARGgR4/edit#
Should we use these Task types and their descriptions from this document in the swagger definition?

**Comment by Alino** [comment]
updated in swagger https://github.com/GALAglobal/TAPICC-API-implementation/commit/b3afbfa6963f9e6068414be5e5c4a3c784f21a36
